services:
  - type: web
    name: studying-by-ai-quiz
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: Studying_by_AI
        sync: false # Bạn sẽ nhập giá trị API Key thực tế trên giao diện Render sau
      - key: PYTHON_VERSION
        value: 3.10.0